=== Technology-Enthusiast/SAPUI5-for-ABAPers/Episode 1/po.dtd
<?xml version="1.0"?>
<!ELEMENT myPOs(po)>
<!ELEMENT po(werks,bukrs)>
<!ELEMENT werks(#PCDATA)>
<!ELEMENT bukrs(#PCDATA)>
<!ATTLIST po id ID #REQUIRED>

=== Technology-Enthusiast/SAPUI5-for-ABAPers/Episode 1/po.xml
<!DOCTYPE myPOs SYSTEM "po.dtd">
<myPOs title = " Our Purchase orders">
    <po id="1">
         <werks>DE01</werks>
        <bukrs>1000</bukrs>
    </po>
    <po id="2">
        <werks>DE01</werks>
        <bukrs>1000</bukrs>
    </po>

    <po id="3">
        <werks>DE01</werks>
        <bukrs>1000</bukrs>
    </po>
</myPOs>
